from Graph_1.creation_graph import Graph
gr = Graph()
gr.edge_to_add('A', 'B')
gr.edge_to_add('A', 'C')
gr.edge_to_add('B', 'D')
gr.edge_to_add('C', 'D')
gr.edge_to_add('C', 'F')
gr.edge_to_add('C', 'E')
gr.edge_to_add('D', 'E')
gr.edge_to_add('D', 'G')
gr.edge_to_add('E', 'H')
gr.edge_to_add('E', 'I')
gr.edge_to_add('E', 'F')
gr.edge_to_add('E', 'G')
gr.edge_to_add('G', 'J')
gr.edge_to_add('G', 'I')
gr.edge_to_add('H', 'J')
print('Введите любую 1 букву ')
ver1 = str(input())
if not (type(ver1)) == str:
    raise TypeError
print(gr.has_eiler(ver1))
gr.visual()
gr.visual_new()
